### PR TITLE
Replaced myself with marcelotrevisani

### PR DESCRIPTION
**Pull request by ivoflipse**
Replaced myself with marcelotrevisani as discussed on Gitter

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ivoflipse** [comment]
Like so @marcelotrevisani?

**Comment by marcelotrevisani** [comment]
> Like so @marcelotrevisani?

Yes sure, you can add me
thanks for maintaining this recipe until these days
:)

**Comment by ivoflipse** [comment]
@marcelotrevisani can I merge the pull request or would you prefer to make the linter happy before merging?

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani can I merge the pull request or would you prefer to make the linter happy before merging?

I can fix it later, no problem
Please go ahead and merge it if you want to :)

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Pull request merged**
